version: "3.9"
services:
    mysql:
        build: ./database/
        restart: always
        environment:
            MYSQL_DATABASE: 'tax_payment_system'
            MYSQL_ROOT_PASSWORD: '1234'
        ports:
            - "3306:3306"
        networks:
            - app-network
    payment_record:
        build: ./payment_record
        ports:
            - "8000:5000"
        depends_on:
            - mysql
        networks:
            - app-network
networks:
    app-network: